[platformio]
default_envs = rody-pet

[env:rody-pet]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags = -DBOARD_HAS_PSRAM
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1 -DFW_VERSION=\"0.3.0-pet\" -DCORE_DEBUG_LEVEL=1 -DRODY_PET_EDITION
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
lib_deps =
  adafruit/Adafruit PWM Servo Driver Library
  adafruit/Adafruit NeoPixel
  lovyan03/LovyanGFX @ ^1.2.0

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17
