[platformio]
default_envs = otto

[env:otto]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags = -DBOARD_HAS_PSRAM
; cổng UART (chip cầu USB) → 0 ; nếu chỉ dùng cổng USB native → 1
build_flags = -DARDUINO_USB_CDC_ON_BOOT=0 -DFW_VERSION=\"0.1.0\" -DCORE_DEBUG_LEVEL=1
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
lib_deps =
  adafruit/Adafruit PWM Servo Driver Library
  adafruit/Adafruit NeoPixel

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17
